Cars/Controllers/SalesController.cs
using Cars.Models;
using Cars.Service;
using Cars.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Cars.Controllers
{
    public class SalesController : Controller
    {
        public OrderServices orderServices { get; set; }      
        private readonly IStringLocalizer<SalesController> localizer;

        public SalesController(OrderServices _orderServices , IStringLocalizer<SalesController> _localizer)
        {
            orderServices = _orderServices;
            localizer = _localizer;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetOrders(int currentPage = 1)
        {

            try
            {              
                return View("Index", orderServices.getOrders(currentPage));
            }
            catch (Exception)
            {
                return View("_CustomError");
            }
        }
        [HttpGet]
        public IActionResult ChangeOrderTablelength(int length)
        {
            try
            {
                return View("Index", orderServices.getOrdersWithChangelength(1, length));
            }
            catch (Exception )
            {
                return View("_CustomError");
            }
        }
        [HttpGet]
        public IActionResult GetOrderLines(int currentPage = 1)
        {

            try
            {
                return View("OrderLines", orderServices.getOrderLines(currentPage));
            }
            catch (Exception)
            {
                return View("_CustomError");
            }
        }
        [HttpGet]
        public IActionResult ChangeOrderLinesTablelength(int length)
        {
            try
            {
                return View("OrderLines", orderServices.getOrderLinesWithChangelength(1, length));
            }
            catch (Exception)
            {
                return View("_CustomError");
            }
        }
        [HttpGet]
        public IActionResult ChangeOrderDraftTablelength(int length)
        {
            try
            {
                return View("Draft", orderServices.getOrdersDraftWithChangelength(1, length));
            }
            catch (Exception)
            {
                return View("_CustomError");
            }
        }
        [HttpGet]
        public IActionResult CreateOrder()
        {

            return View(new OrderViewModel { OrderID =-1});
        }
        [HttpPost]
        public IActionResult CreateOrder(OrderViewModel orderModel)
        {
            //if (!orderModel.saveDraft)
            //{
                if (ModelState.IsValid)
                {
                    long orderId = orderServices.AddOrder(orderModel);
                    if (orderId > 0)
                    {
                        //return View("ViewOrder",orderServices.GetOrderByID(orderId));
                        return RedirectToAction("ViewOrder", new { OrderId = orderId });
                    }
                    else if (orderId == 0)
                    {
                        return View("_CustomError");
                    }
                    else if (orderId == -1)
                    {
                        return View("_CustomError");
                    }
                }
                return View(orderModel);
            //}
            //else
            //{
            //   int status =  orderServices.SaveOrderAsDraft(orderModel);
            //    if(status == 1 )
            //    {
            //        return RedirectToAction("Draft",new { currentPage = 1 });
            //    }
            //    else
            //    {
            //        return View("_CustomError");
            //    }
               
            //}
            
        }
        [HttpGet]
        public IActionResult Draft(int currentPage = 1)
        {
            try
            {
                return View("Draft", orderServices.getOrdersDraft(currentPage));
            }
            catch (Exception)
            {
                return View("_CustomError");
            }
        }
        //[HttpGet]
        //public IActionResult OpenOrderDraft(long OrderDraftId)
        //{
        //    try
        //    {
        //        DraftOrder draft = orderServices.getOrderDraftById(OrderDraftId);
        //        OrderViewModel model = new OrderViewModel()
        //        {
        //            Brand = string.IsNullOrEmpty(draft.Brand) ? null : draft.Brand,
        //            Chases = string.IsNullOrEmpty(draft.Chases) ? null : draft.Chases,
        //            CustomerPhone = string.IsNullOrEmpty(draft.Phone) ? null : draft.Phone,
        //            Model = string.IsNullOrEmpty(draft.Model) ? null : draft.Model,
        //            VehicleName = string.IsNullOrEmpty(draft.Name) ? null : draft.Name,
        //            WithMaintenance = draft.WithMaintenance.HasValue ? draft.WithMaintenance.Value : false,
        //            Year = string.IsNullOrEmpty(draft.Year) ? null : draft.Year,
        //            DraftId = draft.DraftOrderID,
        //            OrderID = -1
        //        };

        //        return View("CreateOrder", model);
        //    }
        //    catch (Exception)
        //    {
        //        return View("_CustomError");
        //    }
        //}
        [HttpGet]
        public IActionResult ViewOrder(long OrderId)
        {
            var order = orderServices.GetOrderByID(OrderId);
            ViewBag.types = orderServices.GetSelectListOrderDetailsType();
            //ViewBag.orderDetails = orderServices.GetOrderDetailsByOrderId(OrderId);
            return View(order);
        }
        [HttpGet]
        public IActionResult SaveAsDraft(long OrderId)
        {
            int status = orderServices.SaveAsDraft(OrderId);
            if (status == 1)
            {
                return RedirectToAction("Draft");
            }


            return View("_CustomError");
        }
        [HttpGet]
        public IActionResult SaveOrder(long OrderId)
        {
            int status = orderServices.SaveOrder(OrderId);
            if (status == 1)
            {
                
                return RedirectToAction("GetOrders");
            }


            return View("_CustomError");
        }

        [HttpPost]
        public IActionResult AddOrderDetails(string Items,int Quantity,int Type ,long orderId)
        {
            if (orderId <= 0)
            {
                return Json(new { status = -1, @object = $"{localizer["ErrorOccurred"]}"}); 
            }
            if (string.IsNullOrEmpty(Items) || Quantity <= 0 || Type <= 0)
            {
                
                   var test = localizer["CheckItemsQuantityAndType"];
                return Json(new { status = -1, @object = $"{localizer["CheckItemsQuantityAndType"]}" }); 
            }

            int status = orderServices.AddOrderDetails(Items,Quantity,Type, orderId);
            if (status == 1)
            {
                try
                {
                    var orderDetails = orderServices.GetOrderDetailsByOrderId(orderId);
                    return Json(new { status = 1, @object = orderDetails });
                }
                catch (Exception)
                {
                    return Json(new { status = -1, @object = $"{localizer["ErrorOccurred"]}" }); 
                }              
               
            }
            else 
            {
                return Json(new { status = -1, @object = $"{localizer["ErrorOccurred"]}" }); 
            }          
            
        }


    }
}

Cars/Views/Sales/CreateOrder.cshtml
@model Cars.ViewModels.OrderViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "Create Order";

}
<div class="card shadow mb-4">
    <div class="card-header">
        <strong class="card-title">@localizer["AddOrderHeader"]</strong>
    </div>
    <div class="card-body">
        <form class="needs-validation" asp-action="CreateOrder" asp-controller="Sales" method="post" id="formCreateOrderHeader">
            <div class="row">
                @*<input type="checkbox" asp-for="saveDraft" id="inputsaveDraft" style="display:none" />*@
                <div class="col-md-6">
                    <div class="form-group mb-4">
                        <label for="simpleinput">@localizer["Chases"]</label>
                        <input onblur="checkChases(this.value)" asp-for="Chases" class="form-control" required />
                        <span asp-validation-for="Chases" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label for="example-email">@localizer["CarName"]</label>
                        <input asp-for="VehicleName" class="form-control" required />
                        <span asp-validation-for="VehicleName" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label for="example-password">@localizer["Phone"]</label>
                        <input asp-for="CustomerPhone" class="form-control" required />
                        <span asp-validation-for="CustomerPhone" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        
                        <div class="row">

                            <div class="col-md-7">
                                <label for="example-palaceholder">@localizer["Maintenance"]   </label>
                                <input asp-for="WithMaintenance" class="form-check-label" />
                                <span asp-validation-for="WithMaintenance" class="text-danger"></span>
                            </div>
                            <div class="col-md-5">
                                <input type="button" class="btn btn-primary" id="btnOpenDetails" onclick="OpenDetails()" value="@localizer["OpenDetails"]"/>
                                <input type="button" class="btn btn-warning" id="btnRemoveDetails" onclick="RemoveDetails()" value="@localizer["RemoveDetails"]"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <div class="row">
                            <div class="col-md-5">
                                <a class="btn btn-danger" style=" width: 100px;" href="~/"> @localizer["Cancel"]</a>
                                <input class="btn btn-success" style=" width: 100px;" type="submit" value="@localizer["Save"]" />
                                @*@if (Model.DraftId.HasValue && Model.DraftId.Value > 0)
                                    {
                                        <input asp-for="DraftId" style="display:none" />
                                    }
                                    else
                                    {
                                        <input class="btn btn-primary" type="button" onclick="SaveOrderAsDraft()" value="@localizer["SaveAsDraft"]" />
                                    }*@
                            </div>
                            <div class="col-md-5"></div>

                            <div class="col-md-2">
                               

                            </div>
                        </div>
                       
                       
                    </div>
                </div> <!-- /.col -->
                <div class="col-md-6" id="carDetails" style="display:none">

                    <div class="form-group mb-3">
                        <label for="example-helping">@localizer["Brand"]</label>
                        <input asp-for="Brand" class="form-control" />
                        <span asp-validation-for="Brand" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label for="example-readonly">@localizer["Model"]</label>
                        <input asp-for="Model" class="form-control" />
                        <span asp-validation-for="Model" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label for="example-disable">@localizer["Year"]</label>
                        <select asp-for="Year" class="form-control" >
                            <option value="" selected>@localizer["Choose"]</option>
                            @for (int i = 1900; i < 2100; i++)
                            {
                                <option value="@i">@i</option>
                            }

                        </select>
                        <span asp-validation-for="Year" class="text-danger"></span>
                    </div>

                 
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
<script>
    ChangeColorSidebarItem("anavbarOrders", "aAddOrderHeader");
    document.getElementById("btnRemoveDetails").style.display = "none";
    let _OpenDetails = false;
    function OpenDetails() {
        _OpenDetails = true;
        document.getElementById("btnOpenDetails").style.display = "none";
        document.getElementById("btnRemoveDetails").style.display = "block";
        checkChases();
    }
    function RemoveDetails() {
        document.getElementById("btnOpenDetails").style.display = "block";
        document.getElementById("btnRemoveDetails").style.display = "none";
        _OpenDetails = false;
        document.getElementById("carDetails").style.display = "none";
        document.getElementById("Year").value = null;
        document.getElementById("Model").value = null;
        document.getElementById("Brand").value = null;
    }

    function checkChases(value) {
        console.log(_OpenDetails);
        if (_OpenDetails) {
            document.getElementById("carDetails").style.display = "block";
        } else {
            if (value.trim().length < 7) {
                document.getElementById("carDetails").style.display = "block";
                document.getElementById("btnRemoveDetails").style.display = "block";
                document.getElementById("btnOpenDetails").style.display = "none";
            } else {
                //document.getElementById("carDetails").style.display = "none";
                //document.getElementById("Year").value = null;
                //document.getElementById("Model").value = null;
                //document.getElementById("Brand").value = null;
            }
        }
       
    }
    //function SaveOrderAsDraft() {
    //    //document.getElementById("inputsaveDraft").value = true;
    //    document.getElementById("inputsaveDraft").checked = true;
    //    document.getElementById("formCreateOrderHeader").submit();
    //}
   
</script>
   
}

Cars/Views/Sales/Draft.cshtml
@model Cars.ViewModels.PagingViewModel<Order>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "Draft";
    int counter = 1;
}

<div class="card shadow">
    <div class="card-body">
        <div class="toolbar">
            <form class="form" id="OrderTablelength" method="get" asp-action="ChangeOrderDraftTablelength" asp-controller="Sales">
                <div class="form-row">
                    <div class="form-group col-auto mr-auto">
                        <label class="my-1 mr-2 sr-only" for="inlineFormCustomSelectPref1">@localizer["Show"]</label>
                        <select name="length" class="custom-select mr-sm-2" onchange="document.getElementById('OrderTablelength').submit();" id="inlineFormCustomSelectPref1">
                            @if (Model.Tablelength == 10)
                            {
                                <option value="10" selected>10</option>
                            }
                            else
                            {
                                <option value="10">10</option>
                            }
                            @if (Model.Tablelength == 25)
                            {
                                <option value="25" selected>25</option>
                            }
                            else
                            {
                                <option value="25">25</option>
                            }
                            @if (Model.Tablelength == 50)
                            {
                                <option value="50" selected>50</option>
                            }
                            else
                            {
                                <option value="50">50</option>
                            }
                            @if (Model.Tablelength == 100)
                            {
                                <option value="100" selected>100</option>
                            }
                            else
                            {
                                <option value="100">100</option>
                            }
                        </select>
                    </div>
                    <div class="form-group col-auto">
                        <label for="search" class="sr-only">Search</label>
                        <input type="text" class="form-control" id="search1" value="" placeholder="Search">
                    </div>
                </div>
            </form>
        </div>
        <!-- table -->
        <table class="table table-borderless table-hover">
            <thead>
                <tr>
                    <th>#</th>
                   
                    <th>@localizer["Name"]</th>
                    <th>@localizer["Phone"]</th>
                   <th>@localizer["Brand"]</th>
                        <th>@localizer["Model"]</th>
                        <th>@localizer["Year"]</th>
                    <th>@localizer["Date"]</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.items)
                {
                    <tr>
                        <td>
                            @counter
                        </td>
                        
                        <td>
                            @item.Vehicle.Name
                        </td>
                        <td>
                            @item.Customer.CustomerContacts.FirstOrDefault().Phone
                        </td>
                        <td>
                    @item.Vehicle.Brand
                </td>
                <td>
                    @item.Vehicle.Model
                </td>
                <td>
                    @item.Vehicle.Year
                </td>
                        <td>
                            @item.DTsCreate
                        </td>
                        <td>
                            <a asp-action="ViewOrder" asp-controller="Sales" asp-route-OrderId="@item.OrderID" class="btn btn-primary btn-sm">@localizer["Show"]</a>
                        </td>


                    </tr>
                    counter++;
                }

            </tbody>
        </table>
        <nav aria-label="Table Paging" class="mb-0 text-muted">
            <ul class="pagination justify-content-center mb-0">
                <li class='page-item @(Model.CurrentPageIndex == 1 ? "disabled":"")' id="dataTable_previous">
                    <a asp-action="Draft" asp-controller="Sales" asp-route-currentPage="@(Model.CurrentPageIndex-1)" class="page-link">@localizer["Previous"]</a>
                </li>
                @*<li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>*@
                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    @if (i != Model.CurrentPageIndex)
                    {
                        <li class="page-item">
                            <a asp-action="Draft" asp-controller="Sales" asp-route-currentPage="@i" class="page-link">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item active">
                            <span class="page-link">@i</span>
                        </li>
                    }


                }
                <li class='page-item @(Model.PageCount == Model.CurrentPageIndex ? "disabled":"")' id="dataTable_next">
                    <a asp-action="Draft" asp-controller="Sales" asp-route-currentPage="@(Model.CurrentPageIndex+1)" class="page-link">@localizer["Next"]</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
@section Scripts {
    <script>
        ChangeColorSidebarItem("anavbarOrders", "aDraftOrderHeader");

    </script>

}

Cars/Views/Sales/Index.cshtml
@model Cars.ViewModels.PagingViewModel<Order>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "Orders";
    int counter = 1;
}

<div class="card shadow">
    <div class="card-body">
        <div class="toolbar">
            <form class="form" id="OrderTablelength" method="get" asp-action="ChangeOrderTablelength" asp-controller="Sales">
                <div class="form-row">
                    <div class="form-group col-auto mr-auto">
                        <label class="my-1 mr-2 sr-only" for="inlineFormCustomSelectPref1">@localizer["Show"]</label>
                        <select name="length" class="custom-select mr-sm-2" onchange="document.getElementById('OrderTablelength').submit();" id="inlineFormCustomSelectPref1">
                            @if (Model.Tablelength == 10)
                            {
                                <option value="10" selected>10</option>
                            }
                            else
                            {
                                <option value="10">10</option>
                            }
                            @if (Model.Tablelength == 25)
                            {
                                <option value="25" selected>25</option>
                            }
                            else
                            {
                                <option value="25">25</option>
                            }
                            @if (Model.Tablelength == 50)
                            {
                                <option value="50" selected>50</option>
                            }
                            else
                            {
                                <option value="50">50</option>
                            }
                            @if (Model.Tablelength == 100)
                            {
                                <option value="100" selected>100</option>
                            }
                            else
                            {
                                <option value="100">100</option>
                            }
                        </select>
                    </div>
                    <div class="form-group col-auto">
                        <label for="search" class="sr-only">Search</label>
                        <input type="text" class="form-control" id="search1" value="" placeholder="Search">
                    </div>
                </div>
            </form>
        </div>
        <!-- table -->
        <table class="table table-borderless table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>@localizer["ID"]</th>
                    <th>@localizer["Name"]</th>
                    <th>@localizer["Phone"]</th>
                    @*<th>@localizer["Brand"]</th>
                    <th>@localizer["Model"]</th>
                    <th>@localizer["Year"]</th>*@
                    <th>@localizer["Date"]</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.items)
                {
                <tr>
                    <td>
                        @counter
                    </td>
                    <td>
                        @item.OrderID
                    </td>
                    <td>
                        @item.Vehicle.Name
                    </td>
                    <td>
                        @item.Customer.CustomerContacts.FirstOrDefault().Phone
                    </td>
                    @*<td>
                        @item.Vehicle.Brand
                    </td>
                    <td>
                        @item.Vehicle.Model
                    </td>
                    <td>
                        @item.Vehicle.Year
                    </td>*@
                    <td>
                        @item.DTsCreate
                    </td>
                    <td>
                        <a asp-action="ViewOrder" asp-controller="Sales" asp-route-OrderId="@item.OrderID" class="btn btn-primary btn-sm">@localizer["Show"]</a>
                    </td>

                    
                </tr>
                    counter++;
                }

            </tbody>
        </table>
        <nav aria-label="Table Paging" class="mb-0 text-muted">
            <ul class="pagination justify-content-center mb-0">
                <li class='page-item @(Model.CurrentPageIndex == 1 ? "disabled":"")' id="dataTable_previous">
                    <a asp-action="GetOrders" asp-controller="Sales" asp-route-currentPage="@(Model.CurrentPageIndex-1)" class="page-link">@localizer["Previous"]</a>
                </li>
                @*<li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>*@
                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    @if (i != Model.CurrentPageIndex)
                    {
                        <li class="page-item">
                            <a asp-action="GetOrders" asp-controller="Sales" asp-route-currentPage="@i" class="page-link">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item active">
                            <span class="page-link">@i</span>
                        </li>
                    }


                }
                <li class='page-item @(Model.PageCount == Model.CurrentPageIndex ? "disabled":"")' id="dataTable_next">
                    <a asp-action="GetOrders" asp-controller="Sales" asp-route-currentPage="@(Model.CurrentPageIndex+1)" class="page-link">@localizer["Next"]</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
@section Scripts {
    <script>
        ChangeColorSidebarItem("anavbarOrders", "aOrderHeaders");

    </script>

}

Cars/Views/Sales/tsetcreate.cshtml
@model Cars.ViewModels.OrderViewModel

@{
    ViewData["Title"] = "tsetcreate";
    Layout = "~/Views/Shared/_AuthenticatedLayout.cshtml";
}

<h1>tsetcreate</h1>

<h4>OrderViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="tsetcreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderID" class="control-label"></label>
                <input asp-for="OrderID" class="form-control" />
                <span asp-validation-for="OrderID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chases" class="control-label"></label>
                <input asp-for="Chases" class="form-control" />
                <span asp-validation-for="Chases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleName" class="control-label"></label>
                <input asp-for="VehicleName" class="form-control" />
                <span asp-validation-for="VehicleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithMaintenance" /> @Html.DisplayNameFor(model => model.WithMaintenance)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}